"""Add AttendanceLog to AttendanceRecord relationship

Revision ID: 08cbacbbc9bf
Revises: add_shift_analysis_fields
Create Date: 2025-05-07 18:30:38.459129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cbacbbc9bf'
down_revision = 'add_shift_analysis_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_record_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'attendance_record', ['attendance_record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('attendance_record_id')

    # ### end Alembic commands ###
