"""Add night_allowance_hours to AttendanceRecord

Revision ID: 76958586561d
Revises: 9a518b5ec483
Create Date: 2025-05-16 12:41:01.607421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76958586561d'
down_revision = '9a518b5ec483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overt_time_weighted', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_column('overt_time_weighted')

    # ### end Alembic commands ###
