"""Add Hikvision device fields

Revision ID: 9a846ad5a73d
Revises: ba148351d994
Create Date: 2025-05-03 11:57:33.158884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a846ad5a73d'
down_revision = 'ba148351d994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('firmware_version', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_device', schema=None) as batch_op:
        batch_op.drop_column('firmware_version')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
