"""add_overtime_rule_and_enhanced_attendance_record

Revision ID: a50784d34b84
Revises: c45e6bc23f9a
Create Date: 2025-05-07 17:38:02.921549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50784d34b84'
down_revision = 'c45e6bc23f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_log_employee_timestamp_log_type')

    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_rule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overtime_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_night_hours', sa.Float(), nullable=True))
        batch_op.drop_index('ix_attendance_record_date')
        batch_op.drop_index('ix_attendance_record_employee_id_date')
        batch_op.create_foreign_key(None, 'overtime_rule', ['overtime_rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_attendance_record_employee_id_date', ['employee_id', 'date'], unique=False)
        batch_op.create_index('ix_attendance_record_date', ['date'], unique=False)
        batch_op.drop_column('overtime_night_hours')
        batch_op.drop_column('overtime_rate')
        batch_op.drop_column('overtime_rule_id')

    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_log_employee_timestamp_log_type', ['employee_id', 'timestamp', 'log_type'], unique=True)

    # ### end Alembic commands ###
